# Generated by Django 6.0.4 on 2026-05-04 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название занятия')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('instructor', models.CharField(default='', max_length=100, verbose_name='Инструктор')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Макс. участников')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('single', 'Разовое занятие'), ('subscription', 'Абонемент'), ('package', 'Пакет занятий')], default='single', max_length=20, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает оплаты'), ('refunded', 'Возвращено')], default='paid', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('sessions_count', models.PositiveIntegerField(default=1, verbose_name='Количество занятий')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('rent_date', models.DateField(verbose_name='Дата аренды')),
                ('hours_rented', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='Часов аренды')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает оплаты'), ('overdue', 'Просрочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Оплата аренды',
                'verbose_name_plural': 'Оплаты аренды',
                'ordering': ['-rent_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата посещения')),
                ('status', models.CharField(choices=[('attended', 'Посетил'), ('cancelled', 'Отменил'), ('no_show', 'Не пришел')], default='attended', max_length=20, verbose_name='Статус')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classsession', verbose_name='Занятие')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'unique_together': {('session', 'client')},
            },
        ),
    ]
