# Generated by Django 6.0.5 on 2026-05-13 07:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Стандартная длительность (мин)')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час')),
                ('color', models.CharField(choices=[('#FF6B6B', 'Красный'), ('#4ECDC4', 'Бирюзовый'), ('#45B7D1', 'Голубой'), ('#96CEB4', 'Зеленый'), ('#FFEAA7', 'Желтый'), ('#DDA0DD', 'Фиолетовый'), ('#FFA07A', 'Оранжевый'), ('#98D8C8', 'Мятный'), ('#F7DC6F', 'Лимонный'), ('#BB8FCE', 'Лавандовый')], default='#4ECDC4', max_length=7, verbose_name='Цвет события')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('student', 'Ученик'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('subscription_remaining', models.PositiveIntegerField(default=0, verbose_name='Остаток абонемента (занятий)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Макс. участников')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторять каждую неделю')),
                ('recurrence_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID серии повторений')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classtype', verbose_name='Занятие')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('single', 'Разовое занятие'), ('subscription', 'Абонемент'), ('package', 'Пакет занятий')], default='single', max_length=20, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает оплаты'), ('refunded', 'Возвращено')], default='paid', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты')),
                ('sessions_count', models.PositiveIntegerField(default=1, verbose_name='Количество занятий')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('rent_date', models.DateField(verbose_name='Дата аренды')),
                ('hours_rented', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='Часов аренды')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает оплаты'), ('overdue', 'Просрочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Оплата аренды',
                'verbose_name_plural': 'Оплаты аренды',
                'ordering': ['-rent_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата посещения')),
                ('status', models.CharField(choices=[('attended', 'Посетил'), ('cancelled', 'Отменил'), ('no_show', 'Не пришел')], default='attended', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classsession', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'unique_together': {('session', 'client')},
            },
        ),
    ]
