# Generated by Django 6.0.5 on 2026-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='color',
            field=models.CharField(default='#3788d8', help_text='Цвет в формате HEX (например, #3788d8)', max_length=7, verbose_name='Цвет в календаре'),
        ),
    ]
