# Generated by Django 6.0.5 on 2026-05-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_remaining',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_subscription_used',
            field=models.BooleanField(default=False, help_text='Если отмечено, занятие оплачено через абонемент', verbose_name='Использован абонемент'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_subscription_available',
            field=models.BooleanField(default=False, help_text='Если отмечено, для этого тарифа можно приобрести абонемент', verbose_name='Доступен абонемент'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость абонемента', max_digits=10, verbose_name='Стоимость абонемента'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='subscription_sessions_count',
            field=models.PositiveIntegerField(default=8, help_text='Стандартное количество занятий в абонементе', verbose_name='Количество занятий в абонементе'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='subscription_validity_days',
            field=models.PositiveIntegerField(default=45, help_text='Срок действия абонемента в днях (по умолчанию 45 дней = 1.5 месяца)', verbose_name='Срок действия абонемента (дней)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение баланса'), ('debit', 'Списание за занятие'), ('refund', 'Возврат средств'), ('adjustment', 'Корректировка баланса'), ('subscription_purchase', 'Покупка абонемента'), ('subscription_use', 'Использование абонемента')], max_length=25, verbose_name='Тип операции'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_total', models.PositiveIntegerField(default=8, verbose_name='Всего занятий')),
                ('sessions_remaining', models.PositiveIntegerField(verbose_name='Осталось занятий')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Дата первого использования абонемента', null=True, verbose_name='Дата активации')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истек'), ('used_up', 'Использован полностью'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('tariff', models.ForeignKey(help_text='Тариф, для которого приобретен абонемент', on_delete=django.db.models.deletion.PROTECT, to='core.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Абонемент, через который оплачено занятие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.subscription', verbose_name='Абонемент'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Абонемент, связанный с этой операцией', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.subscription', verbose_name='Абонемент'),
        ),
    ]
