# Generated by Django 6.0.5 on 2026-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='color',
            field=models.CharField(choices=[('#FF6B6B', 'Красный'), ('#4ECDC4', 'Бирюзовый'), ('#45B7D1', 'Голубой'), ('#96CEB4', 'Зеленый'), ('#FFEAA7', 'Желтый'), ('#DDA0DD', 'Фиолетовый'), ('#FFA07A', 'Оранжевый'), ('#98D8C8', 'Мятный'), ('#F7DC6F', 'Лимонный'), ('#BB8FCE', 'Лавандовый')], default='#4ECDC4', max_length=7, verbose_name='Цвет события'),
        ),
    ]
