# Generated by Django 6.0.5 on 2026-05-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hall_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторять каждую неделю'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID серии повторений'),
        ),
    ]
