# Generated by Django 6.0.5 on 2026-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_subscription_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
