# Generated by Django 6.0.5 on 2026-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя ВКонтакте', null=True, unique=True, verbose_name='VK ID'),
        ),
    ]
