# Generated by Django 6.0.5 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_user_vk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_role', models.CharField(choices=[('student', 'Ученик'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль по умолчанию')),
                ('default_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс по умолчанию')),
                ('default_groups', models.ManyToManyField(blank=True, help_text='Группы прав доступа, которые будут автоматически назначаться новым пользователям', to='auth.group', verbose_name='Группы по умолчанию')),
                ('default_tariffs', models.ManyToManyField(blank=True, help_text='Тарифы, которые будут автоматически назначаться новым пользователям', to='core.tariff', verbose_name='Тарифы по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройки новых пользователей',
                'verbose_name_plural': 'Настройки новых пользователей',
            },
        ),
    ]
