# Generated by Django 6.0.5 on 2026-05-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_options_remove_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
