# Generated by Django 6.0.5 on 2026-05-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_role_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток абонемента (занятий)'),
        ),
    ]
