# Generated by Django 6.0.5 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdefaultsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='max_participants_override',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано, переопределяет макс. количество участников из тарифа для этого занятия', null=True, verbose_name='Переопределение макс. участников'),
        ),
    ]
