# Generated by Django 6.0.5 on 2026-05-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_max_participants_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='tariff',
            field=models.ForeignKey(blank=True, help_text='Тариф для этого занятия', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tariff', verbose_name='Тариф'),
        ),
    ]
